export const STAGES=['DESCOBERTO','VERIFICADO','SELECIONADO','CONTATO_PROGRAMADO','CONTATADO','RESPONDEU','INTERESSADO','PREVIEW','PROPOSTA','FECHADO','PERDIDO','DESCARTADO'] as const;
export type Stage=typeof STAGES[number];
export const STATUSES=['CONFIRMED_WEBSITE','SOCIAL_ONLY','WEBSITE_NOT_FOUND','UNVERIFIED','BROKEN_WEBSITE','POSSIBLE_WEBSITE'] as const;
export type WebsiteStatus=typeof STATUSES[number];
export const statusLabels:Record<WebsiteStatus,string>={CONFIRMED_WEBSITE:'Site confirmado',SOCIAL_ONLY:'Somente redes encontradas',WEBSITE_NOT_FOUND:'Site não encontrado',UNVERIFIED:'Não verificado',BROKEN_WEBSITE:'Site indisponível confirmado',POSSIBLE_WEBSITE:'Possível site'};
export type Lead={id:string;provider:string;externalId:string;name:string;categories:string[];phone:string|null;email:string|null;websites:string[];socials:string[];address:string;city:string;region:string;country:string;latitude:number|null;longitude:number|null;openingHours:string|null;collectedAt:string;status:WebsiteStatus;confidence:number;evidence:Evidence[];saved:boolean;doNotContact:boolean;stage:Stage;scores:Scores;rawData:Record<string,unknown>};
export type Evidence={url:string;title:string;signals:string[];collectedAt:string};
export type Scores={opportunity:number;contactability:number;digitalGap:number;dataConfidence:number;reasons:string[]};
export const defaultWeights={phone:20,email:15,address:10,social:10,missing:18,socialOnly:25,broken:30,possible:8,confidence:20};
export type Weights=typeof defaultWeights;
export function normalize(v:string){return v.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
export function phoneDigits(v:string|null){return (v||'').replace(/\D/g,'');}
export function safeUrl(v:unknown):string|null{if(typeof v!=='string'||v.length>2048)return null;try{const u=new URL(v.includes('://')?v:`https://${v}`);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.port||!u.hostname.includes('.')||u.hostname.endsWith('.local')||u.hostname.endsWith('.internal')||u.hostname.endsWith('.localhost')||u.hostname==='localhost'||u.hostname==='metadata.google.internal'||/^\[|^[\d.]+$/.test(u.hostname))return null;u.hash='';return u.toString();}catch{return null;}}
export function isSocial(v:string){try{const h=new URL(v).hostname.replace(/^www\./,'');return ['instagram.com','facebook.com','fb.com','tiktok.com','x.com','twitter.com','youtube.com','wa.me','linktr.ee'].some(d=>h===d||h.endsWith(`.${d}`));}catch{return false;}}
export function initialStatus(websites:string[]):WebsiteStatus{return websites.some(v=>!isSocial(v))?'POSSIBLE_WEBSITE':'UNVERIFIED';}
export function sameBusiness(a:Lead,b:Lead){if(a.provider===b.provider&&a.externalId===b.externalId)return true;if(a.country!==b.country||normalize(a.city)!==normalize(b.city))return false;const name=normalize(a.name)===normalize(b.name);const phone=phoneDigits(a.phone).length>=8&&phoneDigits(a.phone)===phoneDigits(b.phone);const address=!!a.address&&normalize(a.address)===normalize(b.address);const near=a.latitude!==null&&b.latitude!==null&&a.longitude!==null&&b.longitude!==null&&Math.hypot(a.latitude-b.latitude,a.longitude-b.longitude)<0.0006;return name&&(address||near||(phone&&(!a.address||!b.address)));}
export function dedupe(leads:Lead[]){return leads.filter((l,i)=>!leads.slice(0,i).some(p=>sameBusiness(p,l)));}
export function score(l:Pick<Lead,'phone'|'email'|'address'|'socials'|'status'|'confidence'>,w:Weights=defaultWeights):Scores{const reasons:string[]=[];let contact=0,gap=0,confidence=20;if(l.phone){contact+=65;reasons.push('Telefone publicado na fonte; titularidade comercial não confirmada');}if(l.email){contact+=35;reasons.push('E-mail publicado na fonte');}if(l.address){confidence+=20;reasons.push('Endereço disponível');}if(l.socials.length){gap+=10;reasons.push('Rede social informada');}const bonuses:Record<WebsiteStatus,number>={UNVERIFIED:0,POSSIBLE_WEBSITE:w.possible,CONFIRMED_WEBSITE:0,SOCIAL_ONLY:w.socialOnly,WEBSITE_NOT_FOUND:w.missing,BROKEN_WEBSITE:w.broken};gap+=bonuses[l.status];confidence+=Math.min(60,l.confidence*.6);if(l.status==='UNVERIFIED')reasons.push('Ausência de site na fonte não comprova ausência de site próprio');else reasons.push(statusLabels[l.status]);reasons.push('Reputação e atividade comercial não verificadas');const opportunity=Math.min(100,Math.round((l.phone?w.phone:0)+(l.email?w.email:0)+(l.address?w.address:0)+(l.socials.length?w.social:0)+bonuses[l.status]+l.confidence/100*w.confidence));return{opportunity,contactability:contact,digitalGap:Math.min(100,Math.round(gap*2)),dataConfidence:Math.round(confidence),reasons};}
export type SearchInput={country:string;region:string;city:string;scope:'city'|'region'|'country'|'radius';category:string;custom:string;radius:number;limit:number;provider:'osm'|'geoapify';refresh:boolean;lat?:number;lon?:number;geometryId?:string};
export const categories=[
['barbers','Barbearias','BELEZA','shop','hairdresser','service.beauty.hairdresser'],['salons','Salões','BELEZA','shop','hairdresser','service.beauty.hairdresser'],['beauty','Estética','BELEZA','shop','beauty','service.beauty'],['nails','Manicure','BELEZA','shop','beauty','service.beauty'],['tattoo','Tatuagem','BELEZA','shop','tattoo','service.beauty.tattoo'],
['restaurants','Restaurantes','ALIMENTAÇÃO','amenity','restaurant','catering.restaurant'],['pizza','Pizzarias','ALIMENTAÇÃO','amenity','restaurant','catering.restaurant.pizza'],['snacks','Lanchonetes','ALIMENTAÇÃO','amenity','fast_food','catering.fast_food'],['coffee','Cafeterias','ALIMENTAÇÃO','amenity','cafe','catering.cafe'],
['dentists','Dentistas','SAÚDE','amenity','dentist','healthcare.dentist'],['clinics','Clínicas','SAÚDE','amenity','clinic','healthcare.clinic_or_praxis'],['physio','Fisioterapia','SAÚDE','healthcare','physiotherapist','healthcare.clinic_or_praxis'],
['mechanic','Oficinas','AUTOMOTIVO','shop','car_repair','service.vehicle.repair.car'],['electrical','Autoelétrica','AUTOMOTIVO','shop','car_repair','service.vehicle.repair.car'],['wash','Lava-rápido','AUTOMOTIVO','amenity','car_wash','service.vehicle.car_wash'],['tyres','Borracharia','AUTOMOTIVO','shop','tyres','commercial.vehicle'],
['gyms','Academias','FITNESS','leisure','fitness_centre','sport.fitness.fitness_centre'],['pilates','Pilates','FITNESS','leisure','fitness_centre','sport.fitness.fitness_centre'],['personal','Personal trainers','FITNESS','leisure','fitness_centre','sport.fitness'],
['accountants','Contadores','PROFISSIONAIS','office','accountant','office.accountant'],['architects','Arquitetos','PROFISSIONAIS','office','architect','office.architect'],['lawyers','Advogados','PROFISSIONAIS','office','lawyer','office.lawyer'],['electricians','Eletricistas','PROFISSIONAIS','craft','electrician','service.electrician']] as const;
export function cacheKey(s:SearchInput){return JSON.stringify([s.provider,s.country,normalize(s.region),normalize(s.city),s.scope,s.category,normalize(s.custom),s.radius,s.limit,s.lat??null,s.lon??null,s.geometryId??null]);}
export function verifiedEvidence(l:Lead,items:{url:string;title:string;content:string}[]){const evidence:Evidence[]=[];let best=0,site:string|null=null;let foundSocial=false;for(const i of items){const url=safeUrl(i.url);if(!url)continue;const t=normalize(`${i.title} ${i.content}`);const signals:string[]=[];if(t.includes(normalize(l.name)))signals.push('nome');if(l.city&&t.includes(normalize(l.city)))signals.push('cidade');const p=phoneDigits(l.phone);if(p.length>=8&&(i.content.match(/\+?\d[\d\s().-]{7,25}\d/g)||[]).some(token=>phoneDigits(token).includes(p.slice(-8))))signals.push('telefone');if(l.address&&normalize(l.address).length>8&&t.includes(normalize(l.address)))signals.push('endereço');const points=(signals.includes('nome')?30:0)+(signals.includes('cidade')?15:0)+(signals.includes('telefone')?35:0)+(signals.includes('endereço')?20:0);evidence.push({url,title:i.title.slice(0,200),signals,collectedAt:new Date().toISOString()});if(isSocial(url)){foundSocial=true;continue;}if(points>best){best=points;site=url;}}
// Heuristic evidence index, not a calibrated probability or proof of ownership.
const status:WebsiteStatus=site?(best>=80&&l.websites.some(source=>{try{return new URL(source).hostname===new URL(site!).hostname;}catch{return false;}})&&evidence.some(e=>e.url===site&&e.signals.includes('nome')&&(e.signals.includes('telefone')||e.signals.includes('endereço')))?'CONFIRMED_WEBSITE':'POSSIBLE_WEBSITE'):l.websites.length?'POSSIBLE_WEBSITE':foundSocial?'SOCIAL_ONLY':'WEBSITE_NOT_FOUND';return{evidence,confidence:site?best:30,status,site};}
export type MessageStyle='Curta'|'Profissional'|'Casual'|'WhatsApp'|'E-mail';
export interface OutreachProvider{generate(l:Lead,style:MessageStyle,language:string):string;}
export class TemplateProvider implements OutreachProvider{generate(l:Lead,style:MessageStyle,language:string){const missing=['WEBSITE_NOT_FOUND','SOCIAL_ONLY'].includes(l.status);const concern=missing?' Não localizei um site próprio na minha pesquisa.':'';let message:string;if(language==='en'){message=`Hello, ${l.name} team! I found your business while researching the area.${missing?' I did not find an official website in my search.':''} I build websites for local businesses. May I send a short idea for your business?`;if(style==='Curta')message=`Hi, ${l.name}! I build websites for local businesses. May I send you a short idea?`;if(style==='E-mail')message=`Subject: Website idea for ${l.name}\n\n${message}\n\nThank you for your time.`;return message;}if(language==='es'){message=`¡Hola, equipo de ${l.name}! Encontré su negocio buscando empresas de la zona.${missing?' No encontré un sitio web propio en mi búsqueda.':''} Desarrollo sitios para negocios locales. ¿Puedo enviarles una idea breve?`;if(style==='Curta')message=`¡Hola, ${l.name}! Desarrollo sitios para negocios locales. ¿Puedo enviarles una idea breve?`;if(style==='E-mail')message=`Asunto: Una idea de sitio web para ${l.name}\n\n${message}\n\nGracias por su tiempo.`;return message;}if(style==='Curta')return `Oi, pessoal da ${l.name}! Crio sites para negócios locais. Posso mandar uma ideia rápida para vocês?`;if(style==='Casual')return `Oi, pessoal da ${l.name}, tudo bem? Encontrei vocês pesquisando negócios da região.${concern} Trabalho com sites e pensei em uma ideia para vocês. Posso mostrar?`;message=`Olá, equipe da ${l.name}! Encontrei a empresa enquanto pesquisava negócios da região.${concern} Trabalho com criação de sites para negócios locais. Posso apresentar uma ideia para vocês avaliarem?`;if(style==='WhatsApp')return `Oi, pessoal da ${l.name}! Encontrei vocês pesquisando negócios da região.${concern}\n\nCrio sites para negócios locais. Posso enviar uma ideia rápida para vocês?`;if(style==='E-mail')return `Assunto: Uma ideia de site para ${l.name}\n\n${message}\n\nObrigado pela atenção.`;return message;}}
export function whatsapp(l:Lead,message:string){const p=phoneDigits(l.phone);return p.length>=10&&p.length<=15&&l.phone?.startsWith('+')&&!l.doNotContact?`https://wa.me/${p}?text=${encodeURIComponent(message)}`:null;}
