import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {defaultWeights,type Weights} from './domain';
export class AppError extends Error{constructor(public status:number,message:string){super(message);}}
export function db(){const database=(env as unknown as {DB?:D1Database}).DB;if(!database)throw new AppError(503,'Banco indisponível. Tente novamente.');return database;}
export function secret(name:string){return (env as unknown as Record<string,string>)[name]||process.env[name]||'';}
export async function owner(request?:Request){const user=await getChatGPTUser();if(!user)throw new AppError(401,'Entre com sua conta para acessar os leads.');if(request&&request.method!=='GET'){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin&&origin!=='https://zytrix-leads.guilhermeaugusto2525.chatgpt.site')throw new AppError(403,'Origem da solicitação inválida.');if(!request.headers.get('content-type')?.startsWith('application/json'))throw new AppError(415,'Envie JSON.');}return user.userId;}
export async function body(request:Request){const reader=request.body?.getReader();if(!reader)throw new AppError(400,'Dados ausentes.');let text='',bytes=0;const decoder=new TextDecoder();while(true){const r=await reader.read();if(r.done)break;bytes+=r.value.length;if(bytes>16384){await reader.cancel();throw new AppError(413,'Solicitação muito grande.');}text+=decoder.decode(r.value,{stream:true});}try{return JSON.parse(text);}catch{throw new AppError(400,'JSON inválido.');}}
export function response(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'private, no-store','X-Robots-Tag':'noindex, nofollow','X-Content-Type-Options':'nosniff'}});}
export function failure(e:unknown){return response({error:e instanceof AppError?e.message:'Não foi possível concluir. Tente novamente.'},e instanceof AppError?e.status:503);}
export async function weights(id:string):Promise<Weights>{const r=await db().prepare('SELECT weights FROM settings WHERE owner=?').bind(id).first<{weights:string}>();return r?JSON.parse(r.weights):defaultWeights;}
export async function quota(provider:string,period:string,limit:number,cost=1,interval=0){const now=Date.now();const result=await db().prepare('INSERT INTO usage(provider,period,used,last_at) VALUES(?,?,?,?) ON CONFLICT(provider,period) DO UPDATE SET used=used+excluded.used,last_at=excluded.last_at WHERE used+excluded.used<=? AND last_at<=? RETURNING used').bind(provider,period,cost,now,limit,now-interval).first();if(!result)throw new AppError(429,'Limite gratuito ou intervalo de segurança atingido. Aguarde.');}
export async function limitedJson(url:string,init:RequestInit={},timeout=18000,maxBytes=1_500_000){let res:Response;try{res=await fetch(url,{...init,redirect:'manual',signal:AbortSignal.timeout(timeout)});}catch{throw new AppError(502,'Fonte indisponível ou tempo limite excedido.');}if(!res.ok)throw new AppError(res.status===429?429:502,'A fonte não respondeu. Nenhum resultado foi inventado.');if(Number(res.headers.get('content-length')||0)>maxBytes)throw new AppError(502,'Resposta acima do limite seguro.');const reader=res.body?.getReader();if(!reader)throw new AppError(502,'Resposta vazia.');let size=0,text='';const decoder=new TextDecoder();try{while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>maxBytes){await reader.cancel();throw new AppError(502,'Resposta acima do limite seguro.');}text+=decoder.decode(r.value,{stream:true});}text+=decoder.decode();return JSON.parse(text);}catch(e){if(e instanceof AppError)throw e;throw new AppError(502,'Resposta inválida ou incompleta da fonte.');}}
export const day=()=>new Date().toISOString().slice(0,10);
export const month=()=>new Date().toISOString().slice(0,7);
