import {z} from 'zod';
import {categories,STAGES,STATUSES} from './domain';
export const searchSchema=z.object({country:z.string().regex(/^[A-Z]{2}$/),region:z.string().max(100).default(''),city:z.string().max(100).default(''),scope:z.enum(['city','region','country','radius']).default('city'),category:z.string().refine(v=>categories.some(c=>c[0]===v)),custom:z.string().max(100).default(''),radius:z.number().int().min(1).max(10).default(3),limit:z.number().int().min(1).max(100).default(30),provider:z.enum(['osm','geoapify']).default('osm'),refresh:z.boolean().default(false),locationId:z.string().uuid().optional()}).superRefine((s,c)=>{if((s.scope==='city'||s.scope==='radius')&&!s.city.trim())c.addIssue({code:z.ZodIssueCode.custom,message:'Informe a cidade.'});if(s.scope==='region'&&!s.region.trim())c.addIssue({code:z.ZodIssueCode.custom,message:'Informe a divisão administrativa.'});});
export const mutationSchema=z.discriminatedUnion('action',[
z.object({action:z.literal('save'),id:z.string().uuid()}),z.object({action:z.literal('stage'),id:z.string().uuid(),stage:z.enum(STAGES)}),z.object({action:z.literal('suppress'),id:z.string().uuid(),value:z.boolean()}),z.object({action:z.literal('delete'),id:z.string().uuid()}),
z.object({action:z.literal('edit'),id:z.string().uuid(),name:z.string().min(1).max(200),phone:z.string().max(40).nullable(),email:z.string().email().max(200).nullable(),website:z.string().max(2048).nullable(),address:z.string().max(300)}),
z.object({action:z.literal('confirm'),id:z.string().uuid(),status:z.enum(STATUSES),evidenceUrl:z.string().url().max(2048),note:z.string().min(20).max(500)}),
z.object({action:z.literal('schedule'),id:z.string().uuid(),dueAt:z.string().datetime(),message:z.string().min(1).max(2000),channel:z.enum(['WhatsApp','Telefone','E-mail','Outro'])}),z.object({action:z.literal('complete'),id:z.string().uuid()}),
z.object({action:z.literal('weights'),weights:z.object({phone:z.number().min(0).max(50),email:z.number().min(0).max(50),address:z.number().min(0).max(50),social:z.number().min(0).max(50),missing:z.number().min(0).max(50),socialOnly:z.number().min(0).max(50),broken:z.number().min(0).max(50),possible:z.number().min(0).max(50),confidence:z.number().min(0).max(50)})})]);
