import {sqliteTable,text,integer,index,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),createdAt:text('created_at').notNull()});
export const leads=sqliteTable('leads',{id:text('id').primaryKey(),owner:text('owner').notNull(),provider:text('provider').notNull(),externalId:text('external_id').notNull(),name:text('name').notNull(),city:text('city').notNull(),country:text('country').notNull(),payload:text('payload').notNull(),saved:integer('saved').notNull().default(0),stage:text('stage').notNull().default('DESCOBERTO'),doNotContact:integer('do_not_contact').notNull().default(0),updatedAt:text('updated_at').notNull(),version:text('version').notNull().default('')},t=>[index('lead_owner').on(t.owner),uniqueIndex('lead_source').on(t.owner,t.provider,t.externalId)]);
export const searches=sqliteTable('searches',{id:text('id').primaryKey(),owner:text('owner').notNull(),cacheKey:text('cache_key').notNull(),input:text('input').notNull(),results:text('results').notNull(),createdAt:text('created_at').notNull(),expiresAt:text('expires_at').notNull(),count:integer('count').notNull(),newCount:integer('new_count').notNull(),missingCount:integer('missing_count').notNull(),error:text('error'),estimatedCredits:integer('estimated_credits').notNull()},t=>[index('search_cache').on(t.owner,t.cacheKey,t.expiresAt)]);
export const activities=sqliteTable('activities',{id:text('id').primaryKey(),owner:text('owner').notNull(),leadId:text('lead_id').notNull(),type:text('type').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('activity_owner').on(t.owner,t.leadId)]);
export const scheduledContacts=sqliteTable('scheduled_contacts',{id:text('id').primaryKey(),owner:text('owner').notNull(),leadId:text('lead_id').notNull(),dueAt:text('due_at').notNull(),channel:text('channel').notNull(),message:text('message').notNull(),done:integer('done').notNull().default(0)},t=>[index('schedule_owner').on(t.owner,t.dueAt)]);
export const usage=sqliteTable('usage',{provider:text('provider').notNull(),period:text('period').notNull(),used:integer('used').notNull().default(0),lastAt:integer('last_at').notNull().default(0)},t=>[primaryKey({columns:[t.provider,t.period]})]);
export const settings=sqliteTable('settings',{owner:text('owner').primaryKey(),weights:text('weights').notNull()});
export const locationChoices=sqliteTable('location_choices',{id:text('id').primaryKey(),owner:text('owner').notNull(),query:text('query').notNull(),payload:text('payload').notNull(),expiresAt:text('expires_at').notNull()});
